#!/bin/bash

# setup sh
rm ~/.zshrc
ln -s ~/personal/.dotfiles/.zshrc ~/
# setup tmux
ln -s ~/personal/.dotfiles/.tmux.conf ~/
# alacritty
ln -s ~/personal/.dotfiles/alacritty ~/.config/
# visual studio code
ln -s ~/personal/.dotfiles/code/keybindings.json ~/.config/Code/User/
ln -s ~/personal/.dotfiles/code/settings.json ~/.config/Code/User/
# scripts
# ln -s ~/personal/.dotfiles/bin/ ~/.local/
# keyd
mkdir -p /etc/keyd/
ln -s ~/personal/.dotfiles/ubuntu/default.conf /etc/keyd/
# gnome settings
dconf load /org/gnome/settings-daemon/plugins/media-keys/ < ~/personal/.dotfiles/gnome/custom_shortcuts.dconf
dconf load /org/gnome/desktop/wm/keybindings/ < ~/personal/.dotfiles/gnome/desktop_keybindings.dconf
