#!/bin/bash

# setup sh
rm ~/.zshrc
ln -sv ~/personal/.dotfiles/.zshrc ~/
# setup tmux
ln -sv ~/personal/.dotfiles/.tmux.conf ~/
# kitty
# ln -sv ~/personal/.dotfiles/kitty ~/.config/
# visual studio code
# ln -sv ~/personal/.dotfiles/code/keybindings.json ~/.config/Code/User/
# ln -sv ~/personal/.dotfiles/code/settings.json ~/.config/Code/User/
# autostart script
# mkdir -pv ~/.config/autostart
# ln -sv ~/personal/.dotfiles/shortcuts/autostart.desktop ~/.config/autostart/
# keyd
sudo mkdir -pv /etc/keyd/
sudo ln -sv ~/personal/.dotfiles/default.conf /etc/keyd/
sudo systemctl restart keyd
