#!/bin/bash

dconf load /org/gnome/desktop/wm/keybindings/ < ~/personal/.dotfiles/ubuntu/wm_keybindings.dconf
dconf load /org/gnome/shell/keybindings/ < ~/personal/.dotfiles/ubuntu/shell_keybindings.dconf
dconf load /org/gnome/settings-daemon/plugins/media-keys/ < ~/personal/.dotfiles/ubuntu/media_keys.dconf