#!/bin/bash
export DOTFILES="$HOME/personal/.dotfiles"
export PATH="$HOME/.local/bin:$DOTFILES/bin:$PATH"

zen &
kitty -e tmux &
obsidian &
anki &
todo_obsidian &
toggle_theme automatic &
copyq &

# necesario para poder pausar pomodoro en caso de suspension
# export DISPLAY=:0
# export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$(id -u)/bus
python3 $DOTFILES/scripts/gnome_resume_listener.py &
# python3 $DOTFILES/scripts/pomodoro.py &
(
    sleep 8
    python3 $DOTFILES/bin/eventos.py &
)&
