#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find -L ~/projects ~/university ~/ ~/work ~/personal -mindepth 1 -maxdepth 1 -type d 2>/dev/null | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

tmux_running=$(pgrep tmux)
selected_name=$(basename "$selected" | tr . _)
selected=$(realpath -e "$selected" 2>/dev/null || realpath "$selected" 2>/dev/null || printf "%s" "$selected")

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected 
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected 
fi

# prueba
tmux set-environment -t $selected_name SESSION_ROOT "$selected"
tmux switch-client -t $selected_name
