#!/bin/bash

sudo apt update
sudo apt upgrade

sudo apt install make curl fzf zsh gcc fd-find wl-clipboard zoxide gnome-shell-extension-manager

git remote set-url origin git@github.com:molerocn/.dotfiles.git

chsh
mkdir -pv ~/.local/bin
ln -sv /usr/bin/fdfind ~/.local/bin/fd

# git credentials
git config --global user.email "carlos.molero.n@gmail.com"
git config --global user.name "Juan Carlos Molero"
ssh-keygen -t ed25519 -C "carlos.molero.n@gmail.com"
eval "$(ssh-agent -s)"
ssh-add ~/.ssh/id_ed25519
wl-copy < ~/.ssh/id_ed25519.pub
firefox "https://github.com"

# zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

# .dotfiles
mkdir -pv personal
git clone git@github.com:molerocn/.dotfiles ~/personal/.dotfiles
rm ~/.zshrc
ln -sv ~/personal/.dotfiles/linux/.zshrc ~
sudo mkdir -pv /etc/keyd/
sudo ln -sv ~/personal/.dotfiles/linux/linux.conf /etc/keyd/default.conf
mkdir -pv ~/.config/Code
ln -sv ~/personal/.dotfiles/code ~/.config/Code/User
mkdir -pv ~/.config/autostart
ln -sv ~/personal/.dotfiles/linux/gnome/autostart/autostart.desktop ~/.config/autostart/

# keyd
git clone https://github.com/rvaiya/keyd ~/Downloads/keyd
(cd ~/Downloads/keyd && make && sudo make install)
sudo systemctl enable --now keyd

# shortcuts
dconf load /org/gnome/shell/keybindings/ < ~/personal/.dotfiles/linux/gnome/shortcuts/shell_keybindings.dconf
dconf load /org/gnome/desktop/wm/keybindings/ < ~/personal/.dotfiles/linux/gnome/shortcuts/wm_keybindings.dconf
dconf load /org/gnome/settings-daemon/plugins/media-keys/ < ~/personal/.dotfiles/linux/gnome/shortcuts/media_keys.dconf

# fastest keyboard
gsettings set org.gnome.desktop.peripherals.keyboard repeat-interval 30
gsettings set org.gnome.desktop.peripherals.keyboard delay 250